package com.fidelium.domain;

public class ReceiveHistory extends Result {

    public ReceiveHistory(){

    }

    public ReceiveHistory(String title, String contents){
        this.title = title;
        this.contents = contents;
    }

    private String id;

    private String type;

    private String orderDatetime;

    private String txHash;

    private String status;

    private Integer amount;

    private Double price;

    private Double rate;

    private String syncStatus;

    private String updDatetime;

    private String viewYn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_history.tx_hash
     *
     * @return the value of receive_history.tx_hash
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public String getTxHash() {
        return txHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_history.tx_hash
     *
     * @param txHash the value for receive_history.tx_hash
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setTxHash(String txHash) {
        this.txHash = txHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_history.status
     *
     * @return the value of receive_history.status
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_history.status
     *
     * @param status the value for receive_history.status
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_history.amount
     *
     * @return the value of receive_history.amount
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_history.amount
     *
     * @param amount the value for receive_history.amount
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_history.price
     *
     * @return the value of receive_history.price
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_history.price
     *
     * @param price the value for receive_history.price
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_history.rate
     *
     * @return the value of receive_history.rate
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public Double getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_history.rate
     *
     * @param rate the value for receive_history.rate
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setRate(Double rate) {
        this.rate = rate;
    }

    public String getSyncStatus() {
        return syncStatus;
    }

    public void setSyncStatus(String syncStatus) {
        this.syncStatus = syncStatus;
    }

    public String getUpdDatetime() {
        return updDatetime;
    }

    public void setUpdDatetime(String updDatetime) {
        this.updDatetime = updDatetime;
    }

    public String getViewYn() {
        return viewYn;
    }

    public void setViewYn(String viewYn) {
        this.viewYn = viewYn;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getOrderDatetime() {
        return orderDatetime;
    }

    public void setOrderDatetime(String orderDatetime) {
        this.orderDatetime = orderDatetime;
    }

    @Override public String toString() {
        return "ReceiveHistory{" +
                "id='" + id + '\'' +
                ", type='" + type + '\'' +
                ", orderDatetime='" + orderDatetime + '\'' +
                ", txHash='" + txHash + '\'' +
                ", status='" + status + '\'' +
                ", amount=" + amount +
                ", price=" + price +
                ", rate=" + rate +
                ", syncStatus='" + syncStatus + '\'' +
                ", updDatetime=" + updDatetime +
                ", viewYn='" + viewYn + '\'' +
                '}';
    }
}