package com.fidelium.domain;

public class UserCoin extends Result {


    public UserCoin(){

    }

    public UserCoin(String title, String contents){
        this.title = title;
        this.contents = contents;
    }

    private String id;

    private String type;

    private String coin;

    private String qrPath;

    private String repYn;

    private boolean isRep;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coin.coin
     *
     * @return the value of user_coin.coin
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public String getCoin() {
        return coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coin.coin
     *
     * @param coin the value for user_coin.coin
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setCoin(String coin) {
        this.coin = coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_coin.qr_path
     *
     * @return the value of user_coin.qr_path
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public String getQrPath() {
        return qrPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_coin.qr_path
     *
     * @param qrPath the value for user_coin.qr_path
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setQrPath(String qrPath) {
        this.qrPath = qrPath;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getRepYn() {
        return repYn;
    }

    public void setRepYn(String repYn) {
        this.repYn = repYn;
    }

    public boolean isRep() {
        return isRep;
    }

    public void setRep(boolean isRep) {
        this.isRep = isRep;
    }

    @Override
    public String toString() {
        return "UserCoin{" +
                "id='" + id + '\'' +
                ", type='" + type + '\'' +
                ", coin='" + coin + '\'' +
                ", qrPath='" + qrPath + '\'' +
                ", repYn='" + repYn + '\'' +
                ", isRep=" + isRep +
                '}';
    }
}