package com.fidelium.domain2;

import java.util.Date;

public class TradeHistoryBatchKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_history_batch.id
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_history_batch.type
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_history_batch.trade_datetime
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    private Date tradeDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_history_batch.id
     *
     * @return the value of trade_history_batch.id
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_history_batch.id
     *
     * @param id the value for trade_history_batch.id
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_history_batch.type
     *
     * @return the value of trade_history_batch.type
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_history_batch.type
     *
     * @param type the value for trade_history_batch.type
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_history_batch.trade_datetime
     *
     * @return the value of trade_history_batch.trade_datetime
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public Date getTradeDatetime() {
        return tradeDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_history_batch.trade_datetime
     *
     * @param tradeDatetime the value for trade_history_batch.trade_datetime
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setTradeDatetime(Date tradeDatetime) {
        this.tradeDatetime = tradeDatetime;
    }
}