package com.fidelium.domain2;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.region_yn
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    private String regionYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.region
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.address_yn
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    private String addressYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.address
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.type_yn
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    private String typeYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.type
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id_card
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.currency
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.fidelium_wallet
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    private String fideliumWallet;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.region_yn
     *
     * @return the value of user_info.region_yn
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public String getRegionYn() {
        return regionYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.region_yn
     *
     * @param regionYn the value for user_info.region_yn
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setRegionYn(String regionYn) {
        this.regionYn = regionYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.region
     *
     * @return the value of user_info.region
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.region
     *
     * @param region the value for user_info.region
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.address_yn
     *
     * @return the value of user_info.address_yn
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public String getAddressYn() {
        return addressYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.address_yn
     *
     * @param addressYn the value for user_info.address_yn
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setAddressYn(String addressYn) {
        this.addressYn = addressYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.address
     *
     * @return the value of user_info.address
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.address
     *
     * @param address the value for user_info.address
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.type_yn
     *
     * @return the value of user_info.type_yn
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public String getTypeYn() {
        return typeYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.type_yn
     *
     * @param typeYn the value for user_info.type_yn
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setTypeYn(String typeYn) {
        this.typeYn = typeYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.type
     *
     * @return the value of user_info.type
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.type
     *
     * @param type the value for user_info.type
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id_card
     *
     * @return the value of user_info.id_card
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id_card
     *
     * @param idCard the value for user_info.id_card
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.currency
     *
     * @return the value of user_info.currency
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.currency
     *
     * @param currency the value for user_info.currency
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.fidelium_wallet
     *
     * @return the value of user_info.fidelium_wallet
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public String getFideliumWallet() {
        return fideliumWallet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.fidelium_wallet
     *
     * @param fideliumWallet the value for user_info.fidelium_wallet
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setFideliumWallet(String fideliumWallet) {
        this.fideliumWallet = fideliumWallet;
    }
}