package com.fidelium.domain2;

import java.util.ArrayList;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andOriPasswordIsNull() {
            addCriterion("ori_password is null");
            return (Criteria) this;
        }

        public Criteria andOriPasswordIsNotNull() {
            addCriterion("ori_password is not null");
            return (Criteria) this;
        }

        public Criteria andOriPasswordEqualTo(String value) {
            addCriterion("ori_password =", value, "oriPassword");
            return (Criteria) this;
        }

        public Criteria andOriPasswordNotEqualTo(String value) {
            addCriterion("ori_password <>", value, "oriPassword");
            return (Criteria) this;
        }

        public Criteria andOriPasswordGreaterThan(String value) {
            addCriterion("ori_password >", value, "oriPassword");
            return (Criteria) this;
        }

        public Criteria andOriPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("ori_password >=", value, "oriPassword");
            return (Criteria) this;
        }

        public Criteria andOriPasswordLessThan(String value) {
            addCriterion("ori_password <", value, "oriPassword");
            return (Criteria) this;
        }

        public Criteria andOriPasswordLessThanOrEqualTo(String value) {
            addCriterion("ori_password <=", value, "oriPassword");
            return (Criteria) this;
        }

        public Criteria andOriPasswordLike(String value) {
            addCriterion("ori_password like", value, "oriPassword");
            return (Criteria) this;
        }

        public Criteria andOriPasswordNotLike(String value) {
            addCriterion("ori_password not like", value, "oriPassword");
            return (Criteria) this;
        }

        public Criteria andOriPasswordIn(List<String> values) {
            addCriterion("ori_password in", values, "oriPassword");
            return (Criteria) this;
        }

        public Criteria andOriPasswordNotIn(List<String> values) {
            addCriterion("ori_password not in", values, "oriPassword");
            return (Criteria) this;
        }

        public Criteria andOriPasswordBetween(String value1, String value2) {
            addCriterion("ori_password between", value1, value2, "oriPassword");
            return (Criteria) this;
        }

        public Criteria andOriPasswordNotBetween(String value1, String value2) {
            addCriterion("ori_password not between", value1, value2, "oriPassword");
            return (Criteria) this;
        }

        public Criteria andAuthPasswordIsNull() {
            addCriterion("auth_password is null");
            return (Criteria) this;
        }

        public Criteria andAuthPasswordIsNotNull() {
            addCriterion("auth_password is not null");
            return (Criteria) this;
        }

        public Criteria andAuthPasswordEqualTo(String value) {
            addCriterion("auth_password =", value, "authPassword");
            return (Criteria) this;
        }

        public Criteria andAuthPasswordNotEqualTo(String value) {
            addCriterion("auth_password <>", value, "authPassword");
            return (Criteria) this;
        }

        public Criteria andAuthPasswordGreaterThan(String value) {
            addCriterion("auth_password >", value, "authPassword");
            return (Criteria) this;
        }

        public Criteria andAuthPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("auth_password >=", value, "authPassword");
            return (Criteria) this;
        }

        public Criteria andAuthPasswordLessThan(String value) {
            addCriterion("auth_password <", value, "authPassword");
            return (Criteria) this;
        }

        public Criteria andAuthPasswordLessThanOrEqualTo(String value) {
            addCriterion("auth_password <=", value, "authPassword");
            return (Criteria) this;
        }

        public Criteria andAuthPasswordLike(String value) {
            addCriterion("auth_password like", value, "authPassword");
            return (Criteria) this;
        }

        public Criteria andAuthPasswordNotLike(String value) {
            addCriterion("auth_password not like", value, "authPassword");
            return (Criteria) this;
        }

        public Criteria andAuthPasswordIn(List<String> values) {
            addCriterion("auth_password in", values, "authPassword");
            return (Criteria) this;
        }

        public Criteria andAuthPasswordNotIn(List<String> values) {
            addCriterion("auth_password not in", values, "authPassword");
            return (Criteria) this;
        }

        public Criteria andAuthPasswordBetween(String value1, String value2) {
            addCriterion("auth_password between", value1, value2, "authPassword");
            return (Criteria) this;
        }

        public Criteria andAuthPasswordNotBetween(String value1, String value2) {
            addCriterion("auth_password not between", value1, value2, "authPassword");
            return (Criteria) this;
        }

        public Criteria andAuthOriPasswordIsNull() {
            addCriterion("auth_ori_password is null");
            return (Criteria) this;
        }

        public Criteria andAuthOriPasswordIsNotNull() {
            addCriterion("auth_ori_password is not null");
            return (Criteria) this;
        }

        public Criteria andAuthOriPasswordEqualTo(String value) {
            addCriterion("auth_ori_password =", value, "authOriPassword");
            return (Criteria) this;
        }

        public Criteria andAuthOriPasswordNotEqualTo(String value) {
            addCriterion("auth_ori_password <>", value, "authOriPassword");
            return (Criteria) this;
        }

        public Criteria andAuthOriPasswordGreaterThan(String value) {
            addCriterion("auth_ori_password >", value, "authOriPassword");
            return (Criteria) this;
        }

        public Criteria andAuthOriPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("auth_ori_password >=", value, "authOriPassword");
            return (Criteria) this;
        }

        public Criteria andAuthOriPasswordLessThan(String value) {
            addCriterion("auth_ori_password <", value, "authOriPassword");
            return (Criteria) this;
        }

        public Criteria andAuthOriPasswordLessThanOrEqualTo(String value) {
            addCriterion("auth_ori_password <=", value, "authOriPassword");
            return (Criteria) this;
        }

        public Criteria andAuthOriPasswordLike(String value) {
            addCriterion("auth_ori_password like", value, "authOriPassword");
            return (Criteria) this;
        }

        public Criteria andAuthOriPasswordNotLike(String value) {
            addCriterion("auth_ori_password not like", value, "authOriPassword");
            return (Criteria) this;
        }

        public Criteria andAuthOriPasswordIn(List<String> values) {
            addCriterion("auth_ori_password in", values, "authOriPassword");
            return (Criteria) this;
        }

        public Criteria andAuthOriPasswordNotIn(List<String> values) {
            addCriterion("auth_ori_password not in", values, "authOriPassword");
            return (Criteria) this;
        }

        public Criteria andAuthOriPasswordBetween(String value1, String value2) {
            addCriterion("auth_ori_password between", value1, value2, "authOriPassword");
            return (Criteria) this;
        }

        public Criteria andAuthOriPasswordNotBetween(String value1, String value2) {
            addCriterion("auth_ori_password not between", value1, value2, "authOriPassword");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(String value) {
            addCriterion("birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(String value) {
            addCriterion("birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(String value) {
            addCriterion("birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(String value) {
            addCriterion("birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(String value) {
            addCriterion("birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(String value) {
            addCriterion("birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLike(String value) {
            addCriterion("birthday like", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotLike(String value) {
            addCriterion("birthday not like", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<String> values) {
            addCriterion("birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<String> values) {
            addCriterion("birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(String value1, String value2) {
            addCriterion("birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(String value1, String value2) {
            addCriterion("birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andDelYnIsNull() {
            addCriterion("del_yn is null");
            return (Criteria) this;
        }

        public Criteria andDelYnIsNotNull() {
            addCriterion("del_yn is not null");
            return (Criteria) this;
        }

        public Criteria andDelYnEqualTo(String value) {
            addCriterion("del_yn =", value, "delYn");
            return (Criteria) this;
        }

        public Criteria andDelYnNotEqualTo(String value) {
            addCriterion("del_yn <>", value, "delYn");
            return (Criteria) this;
        }

        public Criteria andDelYnGreaterThan(String value) {
            addCriterion("del_yn >", value, "delYn");
            return (Criteria) this;
        }

        public Criteria andDelYnGreaterThanOrEqualTo(String value) {
            addCriterion("del_yn >=", value, "delYn");
            return (Criteria) this;
        }

        public Criteria andDelYnLessThan(String value) {
            addCriterion("del_yn <", value, "delYn");
            return (Criteria) this;
        }

        public Criteria andDelYnLessThanOrEqualTo(String value) {
            addCriterion("del_yn <=", value, "delYn");
            return (Criteria) this;
        }

        public Criteria andDelYnLike(String value) {
            addCriterion("del_yn like", value, "delYn");
            return (Criteria) this;
        }

        public Criteria andDelYnNotLike(String value) {
            addCriterion("del_yn not like", value, "delYn");
            return (Criteria) this;
        }

        public Criteria andDelYnIn(List<String> values) {
            addCriterion("del_yn in", values, "delYn");
            return (Criteria) this;
        }

        public Criteria andDelYnNotIn(List<String> values) {
            addCriterion("del_yn not in", values, "delYn");
            return (Criteria) this;
        }

        public Criteria andDelYnBetween(String value1, String value2) {
            addCriterion("del_yn between", value1, value2, "delYn");
            return (Criteria) this;
        }

        public Criteria andDelYnNotBetween(String value1, String value2) {
            addCriterion("del_yn not between", value1, value2, "delYn");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonexpiredIsNull() {
            addCriterion("isAccountNonExpired is null");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonexpiredIsNotNull() {
            addCriterion("isAccountNonExpired is not null");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonexpiredEqualTo(Byte value) {
            addCriterion("isAccountNonExpired =", value, "isaccountnonexpired");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonexpiredNotEqualTo(Byte value) {
            addCriterion("isAccountNonExpired <>", value, "isaccountnonexpired");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonexpiredGreaterThan(Byte value) {
            addCriterion("isAccountNonExpired >", value, "isaccountnonexpired");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonexpiredGreaterThanOrEqualTo(Byte value) {
            addCriterion("isAccountNonExpired >=", value, "isaccountnonexpired");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonexpiredLessThan(Byte value) {
            addCriterion("isAccountNonExpired <", value, "isaccountnonexpired");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonexpiredLessThanOrEqualTo(Byte value) {
            addCriterion("isAccountNonExpired <=", value, "isaccountnonexpired");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonexpiredIn(List<Byte> values) {
            addCriterion("isAccountNonExpired in", values, "isaccountnonexpired");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonexpiredNotIn(List<Byte> values) {
            addCriterion("isAccountNonExpired not in", values, "isaccountnonexpired");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonexpiredBetween(Byte value1, Byte value2) {
            addCriterion("isAccountNonExpired between", value1, value2, "isaccountnonexpired");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonexpiredNotBetween(Byte value1, Byte value2) {
            addCriterion("isAccountNonExpired not between", value1, value2, "isaccountnonexpired");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonlockedIsNull() {
            addCriterion("isAccountNonLocked is null");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonlockedIsNotNull() {
            addCriterion("isAccountNonLocked is not null");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonlockedEqualTo(Byte value) {
            addCriterion("isAccountNonLocked =", value, "isaccountnonlocked");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonlockedNotEqualTo(Byte value) {
            addCriterion("isAccountNonLocked <>", value, "isaccountnonlocked");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonlockedGreaterThan(Byte value) {
            addCriterion("isAccountNonLocked >", value, "isaccountnonlocked");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonlockedGreaterThanOrEqualTo(Byte value) {
            addCriterion("isAccountNonLocked >=", value, "isaccountnonlocked");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonlockedLessThan(Byte value) {
            addCriterion("isAccountNonLocked <", value, "isaccountnonlocked");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonlockedLessThanOrEqualTo(Byte value) {
            addCriterion("isAccountNonLocked <=", value, "isaccountnonlocked");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonlockedIn(List<Byte> values) {
            addCriterion("isAccountNonLocked in", values, "isaccountnonlocked");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonlockedNotIn(List<Byte> values) {
            addCriterion("isAccountNonLocked not in", values, "isaccountnonlocked");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonlockedBetween(Byte value1, Byte value2) {
            addCriterion("isAccountNonLocked between", value1, value2, "isaccountnonlocked");
            return (Criteria) this;
        }

        public Criteria andIsaccountnonlockedNotBetween(Byte value1, Byte value2) {
            addCriterion("isAccountNonLocked not between", value1, value2, "isaccountnonlocked");
            return (Criteria) this;
        }

        public Criteria andIscredentialsnonexpiredIsNull() {
            addCriterion("isCredentialsNonExpired is null");
            return (Criteria) this;
        }

        public Criteria andIscredentialsnonexpiredIsNotNull() {
            addCriterion("isCredentialsNonExpired is not null");
            return (Criteria) this;
        }

        public Criteria andIscredentialsnonexpiredEqualTo(Byte value) {
            addCriterion("isCredentialsNonExpired =", value, "iscredentialsnonexpired");
            return (Criteria) this;
        }

        public Criteria andIscredentialsnonexpiredNotEqualTo(Byte value) {
            addCriterion("isCredentialsNonExpired <>", value, "iscredentialsnonexpired");
            return (Criteria) this;
        }

        public Criteria andIscredentialsnonexpiredGreaterThan(Byte value) {
            addCriterion("isCredentialsNonExpired >", value, "iscredentialsnonexpired");
            return (Criteria) this;
        }

        public Criteria andIscredentialsnonexpiredGreaterThanOrEqualTo(Byte value) {
            addCriterion("isCredentialsNonExpired >=", value, "iscredentialsnonexpired");
            return (Criteria) this;
        }

        public Criteria andIscredentialsnonexpiredLessThan(Byte value) {
            addCriterion("isCredentialsNonExpired <", value, "iscredentialsnonexpired");
            return (Criteria) this;
        }

        public Criteria andIscredentialsnonexpiredLessThanOrEqualTo(Byte value) {
            addCriterion("isCredentialsNonExpired <=", value, "iscredentialsnonexpired");
            return (Criteria) this;
        }

        public Criteria andIscredentialsnonexpiredIn(List<Byte> values) {
            addCriterion("isCredentialsNonExpired in", values, "iscredentialsnonexpired");
            return (Criteria) this;
        }

        public Criteria andIscredentialsnonexpiredNotIn(List<Byte> values) {
            addCriterion("isCredentialsNonExpired not in", values, "iscredentialsnonexpired");
            return (Criteria) this;
        }

        public Criteria andIscredentialsnonexpiredBetween(Byte value1, Byte value2) {
            addCriterion("isCredentialsNonExpired between", value1, value2, "iscredentialsnonexpired");
            return (Criteria) this;
        }

        public Criteria andIscredentialsnonexpiredNotBetween(Byte value1, Byte value2) {
            addCriterion("isCredentialsNonExpired not between", value1, value2, "iscredentialsnonexpired");
            return (Criteria) this;
        }

        public Criteria andIsenabledIsNull() {
            addCriterion("isEnabled is null");
            return (Criteria) this;
        }

        public Criteria andIsenabledIsNotNull() {
            addCriterion("isEnabled is not null");
            return (Criteria) this;
        }

        public Criteria andIsenabledEqualTo(Byte value) {
            addCriterion("isEnabled =", value, "isenabled");
            return (Criteria) this;
        }

        public Criteria andIsenabledNotEqualTo(Byte value) {
            addCriterion("isEnabled <>", value, "isenabled");
            return (Criteria) this;
        }

        public Criteria andIsenabledGreaterThan(Byte value) {
            addCriterion("isEnabled >", value, "isenabled");
            return (Criteria) this;
        }

        public Criteria andIsenabledGreaterThanOrEqualTo(Byte value) {
            addCriterion("isEnabled >=", value, "isenabled");
            return (Criteria) this;
        }

        public Criteria andIsenabledLessThan(Byte value) {
            addCriterion("isEnabled <", value, "isenabled");
            return (Criteria) this;
        }

        public Criteria andIsenabledLessThanOrEqualTo(Byte value) {
            addCriterion("isEnabled <=", value, "isenabled");
            return (Criteria) this;
        }

        public Criteria andIsenabledIn(List<Byte> values) {
            addCriterion("isEnabled in", values, "isenabled");
            return (Criteria) this;
        }

        public Criteria andIsenabledNotIn(List<Byte> values) {
            addCriterion("isEnabled not in", values, "isenabled");
            return (Criteria) this;
        }

        public Criteria andIsenabledBetween(Byte value1, Byte value2) {
            addCriterion("isEnabled between", value1, value2, "isenabled");
            return (Criteria) this;
        }

        public Criteria andIsenabledNotBetween(Byte value1, Byte value2) {
            addCriterion("isEnabled not between", value1, value2, "isenabled");
            return (Criteria) this;
        }

        public Criteria andReceiveYnIsNull() {
            addCriterion("receive_yn is null");
            return (Criteria) this;
        }

        public Criteria andReceiveYnIsNotNull() {
            addCriterion("receive_yn is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveYnEqualTo(String value) {
            addCriterion("receive_yn =", value, "receiveYn");
            return (Criteria) this;
        }

        public Criteria andReceiveYnNotEqualTo(String value) {
            addCriterion("receive_yn <>", value, "receiveYn");
            return (Criteria) this;
        }

        public Criteria andReceiveYnGreaterThan(String value) {
            addCriterion("receive_yn >", value, "receiveYn");
            return (Criteria) this;
        }

        public Criteria andReceiveYnGreaterThanOrEqualTo(String value) {
            addCriterion("receive_yn >=", value, "receiveYn");
            return (Criteria) this;
        }

        public Criteria andReceiveYnLessThan(String value) {
            addCriterion("receive_yn <", value, "receiveYn");
            return (Criteria) this;
        }

        public Criteria andReceiveYnLessThanOrEqualTo(String value) {
            addCriterion("receive_yn <=", value, "receiveYn");
            return (Criteria) this;
        }

        public Criteria andReceiveYnLike(String value) {
            addCriterion("receive_yn like", value, "receiveYn");
            return (Criteria) this;
        }

        public Criteria andReceiveYnNotLike(String value) {
            addCriterion("receive_yn not like", value, "receiveYn");
            return (Criteria) this;
        }

        public Criteria andReceiveYnIn(List<String> values) {
            addCriterion("receive_yn in", values, "receiveYn");
            return (Criteria) this;
        }

        public Criteria andReceiveYnNotIn(List<String> values) {
            addCriterion("receive_yn not in", values, "receiveYn");
            return (Criteria) this;
        }

        public Criteria andReceiveYnBetween(String value1, String value2) {
            addCriterion("receive_yn between", value1, value2, "receiveYn");
            return (Criteria) this;
        }

        public Criteria andReceiveYnNotBetween(String value1, String value2) {
            addCriterion("receive_yn not between", value1, value2, "receiveYn");
            return (Criteria) this;
        }

        public Criteria andUserExt1IsNull() {
            addCriterion("user_ext1 is null");
            return (Criteria) this;
        }

        public Criteria andUserExt1IsNotNull() {
            addCriterion("user_ext1 is not null");
            return (Criteria) this;
        }

        public Criteria andUserExt1EqualTo(String value) {
            addCriterion("user_ext1 =", value, "userExt1");
            return (Criteria) this;
        }

        public Criteria andUserExt1NotEqualTo(String value) {
            addCriterion("user_ext1 <>", value, "userExt1");
            return (Criteria) this;
        }

        public Criteria andUserExt1GreaterThan(String value) {
            addCriterion("user_ext1 >", value, "userExt1");
            return (Criteria) this;
        }

        public Criteria andUserExt1GreaterThanOrEqualTo(String value) {
            addCriterion("user_ext1 >=", value, "userExt1");
            return (Criteria) this;
        }

        public Criteria andUserExt1LessThan(String value) {
            addCriterion("user_ext1 <", value, "userExt1");
            return (Criteria) this;
        }

        public Criteria andUserExt1LessThanOrEqualTo(String value) {
            addCriterion("user_ext1 <=", value, "userExt1");
            return (Criteria) this;
        }

        public Criteria andUserExt1Like(String value) {
            addCriterion("user_ext1 like", value, "userExt1");
            return (Criteria) this;
        }

        public Criteria andUserExt1NotLike(String value) {
            addCriterion("user_ext1 not like", value, "userExt1");
            return (Criteria) this;
        }

        public Criteria andUserExt1In(List<String> values) {
            addCriterion("user_ext1 in", values, "userExt1");
            return (Criteria) this;
        }

        public Criteria andUserExt1NotIn(List<String> values) {
            addCriterion("user_ext1 not in", values, "userExt1");
            return (Criteria) this;
        }

        public Criteria andUserExt1Between(String value1, String value2) {
            addCriterion("user_ext1 between", value1, value2, "userExt1");
            return (Criteria) this;
        }

        public Criteria andUserExt1NotBetween(String value1, String value2) {
            addCriterion("user_ext1 not between", value1, value2, "userExt1");
            return (Criteria) this;
        }

        public Criteria andUserExt2IsNull() {
            addCriterion("user_ext2 is null");
            return (Criteria) this;
        }

        public Criteria andUserExt2IsNotNull() {
            addCriterion("user_ext2 is not null");
            return (Criteria) this;
        }

        public Criteria andUserExt2EqualTo(String value) {
            addCriterion("user_ext2 =", value, "userExt2");
            return (Criteria) this;
        }

        public Criteria andUserExt2NotEqualTo(String value) {
            addCriterion("user_ext2 <>", value, "userExt2");
            return (Criteria) this;
        }

        public Criteria andUserExt2GreaterThan(String value) {
            addCriterion("user_ext2 >", value, "userExt2");
            return (Criteria) this;
        }

        public Criteria andUserExt2GreaterThanOrEqualTo(String value) {
            addCriterion("user_ext2 >=", value, "userExt2");
            return (Criteria) this;
        }

        public Criteria andUserExt2LessThan(String value) {
            addCriterion("user_ext2 <", value, "userExt2");
            return (Criteria) this;
        }

        public Criteria andUserExt2LessThanOrEqualTo(String value) {
            addCriterion("user_ext2 <=", value, "userExt2");
            return (Criteria) this;
        }

        public Criteria andUserExt2Like(String value) {
            addCriterion("user_ext2 like", value, "userExt2");
            return (Criteria) this;
        }

        public Criteria andUserExt2NotLike(String value) {
            addCriterion("user_ext2 not like", value, "userExt2");
            return (Criteria) this;
        }

        public Criteria andUserExt2In(List<String> values) {
            addCriterion("user_ext2 in", values, "userExt2");
            return (Criteria) this;
        }

        public Criteria andUserExt2NotIn(List<String> values) {
            addCriterion("user_ext2 not in", values, "userExt2");
            return (Criteria) this;
        }

        public Criteria andUserExt2Between(String value1, String value2) {
            addCriterion("user_ext2 between", value1, value2, "userExt2");
            return (Criteria) this;
        }

        public Criteria andUserExt2NotBetween(String value1, String value2) {
            addCriterion("user_ext2 not between", value1, value2, "userExt2");
            return (Criteria) this;
        }

        public Criteria andUserExt3IsNull() {
            addCriterion("user_ext3 is null");
            return (Criteria) this;
        }

        public Criteria andUserExt3IsNotNull() {
            addCriterion("user_ext3 is not null");
            return (Criteria) this;
        }

        public Criteria andUserExt3EqualTo(String value) {
            addCriterion("user_ext3 =", value, "userExt3");
            return (Criteria) this;
        }

        public Criteria andUserExt3NotEqualTo(String value) {
            addCriterion("user_ext3 <>", value, "userExt3");
            return (Criteria) this;
        }

        public Criteria andUserExt3GreaterThan(String value) {
            addCriterion("user_ext3 >", value, "userExt3");
            return (Criteria) this;
        }

        public Criteria andUserExt3GreaterThanOrEqualTo(String value) {
            addCriterion("user_ext3 >=", value, "userExt3");
            return (Criteria) this;
        }

        public Criteria andUserExt3LessThan(String value) {
            addCriterion("user_ext3 <", value, "userExt3");
            return (Criteria) this;
        }

        public Criteria andUserExt3LessThanOrEqualTo(String value) {
            addCriterion("user_ext3 <=", value, "userExt3");
            return (Criteria) this;
        }

        public Criteria andUserExt3Like(String value) {
            addCriterion("user_ext3 like", value, "userExt3");
            return (Criteria) this;
        }

        public Criteria andUserExt3NotLike(String value) {
            addCriterion("user_ext3 not like", value, "userExt3");
            return (Criteria) this;
        }

        public Criteria andUserExt3In(List<String> values) {
            addCriterion("user_ext3 in", values, "userExt3");
            return (Criteria) this;
        }

        public Criteria andUserExt3NotIn(List<String> values) {
            addCriterion("user_ext3 not in", values, "userExt3");
            return (Criteria) this;
        }

        public Criteria andUserExt3Between(String value1, String value2) {
            addCriterion("user_ext3 between", value1, value2, "userExt3");
            return (Criteria) this;
        }

        public Criteria andUserExt3NotBetween(String value1, String value2) {
            addCriterion("user_ext3 not between", value1, value2, "userExt3");
            return (Criteria) this;
        }

        public Criteria andUserExt4IsNull() {
            addCriterion("user_ext4 is null");
            return (Criteria) this;
        }

        public Criteria andUserExt4IsNotNull() {
            addCriterion("user_ext4 is not null");
            return (Criteria) this;
        }

        public Criteria andUserExt4EqualTo(String value) {
            addCriterion("user_ext4 =", value, "userExt4");
            return (Criteria) this;
        }

        public Criteria andUserExt4NotEqualTo(String value) {
            addCriterion("user_ext4 <>", value, "userExt4");
            return (Criteria) this;
        }

        public Criteria andUserExt4GreaterThan(String value) {
            addCriterion("user_ext4 >", value, "userExt4");
            return (Criteria) this;
        }

        public Criteria andUserExt4GreaterThanOrEqualTo(String value) {
            addCriterion("user_ext4 >=", value, "userExt4");
            return (Criteria) this;
        }

        public Criteria andUserExt4LessThan(String value) {
            addCriterion("user_ext4 <", value, "userExt4");
            return (Criteria) this;
        }

        public Criteria andUserExt4LessThanOrEqualTo(String value) {
            addCriterion("user_ext4 <=", value, "userExt4");
            return (Criteria) this;
        }

        public Criteria andUserExt4Like(String value) {
            addCriterion("user_ext4 like", value, "userExt4");
            return (Criteria) this;
        }

        public Criteria andUserExt4NotLike(String value) {
            addCriterion("user_ext4 not like", value, "userExt4");
            return (Criteria) this;
        }

        public Criteria andUserExt4In(List<String> values) {
            addCriterion("user_ext4 in", values, "userExt4");
            return (Criteria) this;
        }

        public Criteria andUserExt4NotIn(List<String> values) {
            addCriterion("user_ext4 not in", values, "userExt4");
            return (Criteria) this;
        }

        public Criteria andUserExt4Between(String value1, String value2) {
            addCriterion("user_ext4 between", value1, value2, "userExt4");
            return (Criteria) this;
        }

        public Criteria andUserExt4NotBetween(String value1, String value2) {
            addCriterion("user_ext4 not between", value1, value2, "userExt4");
            return (Criteria) this;
        }

        public Criteria andUserExt5IsNull() {
            addCriterion("user_ext5 is null");
            return (Criteria) this;
        }

        public Criteria andUserExt5IsNotNull() {
            addCriterion("user_ext5 is not null");
            return (Criteria) this;
        }

        public Criteria andUserExt5EqualTo(String value) {
            addCriterion("user_ext5 =", value, "userExt5");
            return (Criteria) this;
        }

        public Criteria andUserExt5NotEqualTo(String value) {
            addCriterion("user_ext5 <>", value, "userExt5");
            return (Criteria) this;
        }

        public Criteria andUserExt5GreaterThan(String value) {
            addCriterion("user_ext5 >", value, "userExt5");
            return (Criteria) this;
        }

        public Criteria andUserExt5GreaterThanOrEqualTo(String value) {
            addCriterion("user_ext5 >=", value, "userExt5");
            return (Criteria) this;
        }

        public Criteria andUserExt5LessThan(String value) {
            addCriterion("user_ext5 <", value, "userExt5");
            return (Criteria) this;
        }

        public Criteria andUserExt5LessThanOrEqualTo(String value) {
            addCriterion("user_ext5 <=", value, "userExt5");
            return (Criteria) this;
        }

        public Criteria andUserExt5Like(String value) {
            addCriterion("user_ext5 like", value, "userExt5");
            return (Criteria) this;
        }

        public Criteria andUserExt5NotLike(String value) {
            addCriterion("user_ext5 not like", value, "userExt5");
            return (Criteria) this;
        }

        public Criteria andUserExt5In(List<String> values) {
            addCriterion("user_ext5 in", values, "userExt5");
            return (Criteria) this;
        }

        public Criteria andUserExt5NotIn(List<String> values) {
            addCriterion("user_ext5 not in", values, "userExt5");
            return (Criteria) this;
        }

        public Criteria andUserExt5Between(String value1, String value2) {
            addCriterion("user_ext5 between", value1, value2, "userExt5");
            return (Criteria) this;
        }

        public Criteria andUserExt5NotBetween(String value1, String value2) {
            addCriterion("user_ext5 not between", value1, value2, "userExt5");
            return (Criteria) this;
        }

        public Criteria andUserExt6IsNull() {
            addCriterion("user_ext6 is null");
            return (Criteria) this;
        }

        public Criteria andUserExt6IsNotNull() {
            addCriterion("user_ext6 is not null");
            return (Criteria) this;
        }

        public Criteria andUserExt6EqualTo(String value) {
            addCriterion("user_ext6 =", value, "userExt6");
            return (Criteria) this;
        }

        public Criteria andUserExt6NotEqualTo(String value) {
            addCriterion("user_ext6 <>", value, "userExt6");
            return (Criteria) this;
        }

        public Criteria andUserExt6GreaterThan(String value) {
            addCriterion("user_ext6 >", value, "userExt6");
            return (Criteria) this;
        }

        public Criteria andUserExt6GreaterThanOrEqualTo(String value) {
            addCriterion("user_ext6 >=", value, "userExt6");
            return (Criteria) this;
        }

        public Criteria andUserExt6LessThan(String value) {
            addCriterion("user_ext6 <", value, "userExt6");
            return (Criteria) this;
        }

        public Criteria andUserExt6LessThanOrEqualTo(String value) {
            addCriterion("user_ext6 <=", value, "userExt6");
            return (Criteria) this;
        }

        public Criteria andUserExt6Like(String value) {
            addCriterion("user_ext6 like", value, "userExt6");
            return (Criteria) this;
        }

        public Criteria andUserExt6NotLike(String value) {
            addCriterion("user_ext6 not like", value, "userExt6");
            return (Criteria) this;
        }

        public Criteria andUserExt6In(List<String> values) {
            addCriterion("user_ext6 in", values, "userExt6");
            return (Criteria) this;
        }

        public Criteria andUserExt6NotIn(List<String> values) {
            addCriterion("user_ext6 not in", values, "userExt6");
            return (Criteria) this;
        }

        public Criteria andUserExt6Between(String value1, String value2) {
            addCriterion("user_ext6 between", value1, value2, "userExt6");
            return (Criteria) this;
        }

        public Criteria andUserExt6NotBetween(String value1, String value2) {
            addCriterion("user_ext6 not between", value1, value2, "userExt6");
            return (Criteria) this;
        }

        public Criteria andUserExt7IsNull() {
            addCriterion("user_ext7 is null");
            return (Criteria) this;
        }

        public Criteria andUserExt7IsNotNull() {
            addCriterion("user_ext7 is not null");
            return (Criteria) this;
        }

        public Criteria andUserExt7EqualTo(String value) {
            addCriterion("user_ext7 =", value, "userExt7");
            return (Criteria) this;
        }

        public Criteria andUserExt7NotEqualTo(String value) {
            addCriterion("user_ext7 <>", value, "userExt7");
            return (Criteria) this;
        }

        public Criteria andUserExt7GreaterThan(String value) {
            addCriterion("user_ext7 >", value, "userExt7");
            return (Criteria) this;
        }

        public Criteria andUserExt7GreaterThanOrEqualTo(String value) {
            addCriterion("user_ext7 >=", value, "userExt7");
            return (Criteria) this;
        }

        public Criteria andUserExt7LessThan(String value) {
            addCriterion("user_ext7 <", value, "userExt7");
            return (Criteria) this;
        }

        public Criteria andUserExt7LessThanOrEqualTo(String value) {
            addCriterion("user_ext7 <=", value, "userExt7");
            return (Criteria) this;
        }

        public Criteria andUserExt7Like(String value) {
            addCriterion("user_ext7 like", value, "userExt7");
            return (Criteria) this;
        }

        public Criteria andUserExt7NotLike(String value) {
            addCriterion("user_ext7 not like", value, "userExt7");
            return (Criteria) this;
        }

        public Criteria andUserExt7In(List<String> values) {
            addCriterion("user_ext7 in", values, "userExt7");
            return (Criteria) this;
        }

        public Criteria andUserExt7NotIn(List<String> values) {
            addCriterion("user_ext7 not in", values, "userExt7");
            return (Criteria) this;
        }

        public Criteria andUserExt7Between(String value1, String value2) {
            addCriterion("user_ext7 between", value1, value2, "userExt7");
            return (Criteria) this;
        }

        public Criteria andUserExt7NotBetween(String value1, String value2) {
            addCriterion("user_ext7 not between", value1, value2, "userExt7");
            return (Criteria) this;
        }

        public Criteria andUserExt8IsNull() {
            addCriterion("user_ext8 is null");
            return (Criteria) this;
        }

        public Criteria andUserExt8IsNotNull() {
            addCriterion("user_ext8 is not null");
            return (Criteria) this;
        }

        public Criteria andUserExt8EqualTo(String value) {
            addCriterion("user_ext8 =", value, "userExt8");
            return (Criteria) this;
        }

        public Criteria andUserExt8NotEqualTo(String value) {
            addCriterion("user_ext8 <>", value, "userExt8");
            return (Criteria) this;
        }

        public Criteria andUserExt8GreaterThan(String value) {
            addCriterion("user_ext8 >", value, "userExt8");
            return (Criteria) this;
        }

        public Criteria andUserExt8GreaterThanOrEqualTo(String value) {
            addCriterion("user_ext8 >=", value, "userExt8");
            return (Criteria) this;
        }

        public Criteria andUserExt8LessThan(String value) {
            addCriterion("user_ext8 <", value, "userExt8");
            return (Criteria) this;
        }

        public Criteria andUserExt8LessThanOrEqualTo(String value) {
            addCriterion("user_ext8 <=", value, "userExt8");
            return (Criteria) this;
        }

        public Criteria andUserExt8Like(String value) {
            addCriterion("user_ext8 like", value, "userExt8");
            return (Criteria) this;
        }

        public Criteria andUserExt8NotLike(String value) {
            addCriterion("user_ext8 not like", value, "userExt8");
            return (Criteria) this;
        }

        public Criteria andUserExt8In(List<String> values) {
            addCriterion("user_ext8 in", values, "userExt8");
            return (Criteria) this;
        }

        public Criteria andUserExt8NotIn(List<String> values) {
            addCriterion("user_ext8 not in", values, "userExt8");
            return (Criteria) this;
        }

        public Criteria andUserExt8Between(String value1, String value2) {
            addCriterion("user_ext8 between", value1, value2, "userExt8");
            return (Criteria) this;
        }

        public Criteria andUserExt8NotBetween(String value1, String value2) {
            addCriterion("user_ext8 not between", value1, value2, "userExt8");
            return (Criteria) this;
        }

        public Criteria andUserExt9IsNull() {
            addCriterion("user_ext9 is null");
            return (Criteria) this;
        }

        public Criteria andUserExt9IsNotNull() {
            addCriterion("user_ext9 is not null");
            return (Criteria) this;
        }

        public Criteria andUserExt9EqualTo(String value) {
            addCriterion("user_ext9 =", value, "userExt9");
            return (Criteria) this;
        }

        public Criteria andUserExt9NotEqualTo(String value) {
            addCriterion("user_ext9 <>", value, "userExt9");
            return (Criteria) this;
        }

        public Criteria andUserExt9GreaterThan(String value) {
            addCriterion("user_ext9 >", value, "userExt9");
            return (Criteria) this;
        }

        public Criteria andUserExt9GreaterThanOrEqualTo(String value) {
            addCriterion("user_ext9 >=", value, "userExt9");
            return (Criteria) this;
        }

        public Criteria andUserExt9LessThan(String value) {
            addCriterion("user_ext9 <", value, "userExt9");
            return (Criteria) this;
        }

        public Criteria andUserExt9LessThanOrEqualTo(String value) {
            addCriterion("user_ext9 <=", value, "userExt9");
            return (Criteria) this;
        }

        public Criteria andUserExt9Like(String value) {
            addCriterion("user_ext9 like", value, "userExt9");
            return (Criteria) this;
        }

        public Criteria andUserExt9NotLike(String value) {
            addCriterion("user_ext9 not like", value, "userExt9");
            return (Criteria) this;
        }

        public Criteria andUserExt9In(List<String> values) {
            addCriterion("user_ext9 in", values, "userExt9");
            return (Criteria) this;
        }

        public Criteria andUserExt9NotIn(List<String> values) {
            addCriterion("user_ext9 not in", values, "userExt9");
            return (Criteria) this;
        }

        public Criteria andUserExt9Between(String value1, String value2) {
            addCriterion("user_ext9 between", value1, value2, "userExt9");
            return (Criteria) this;
        }

        public Criteria andUserExt9NotBetween(String value1, String value2) {
            addCriterion("user_ext9 not between", value1, value2, "userExt9");
            return (Criteria) this;
        }

        public Criteria andUserExt10IsNull() {
            addCriterion("user_ext10 is null");
            return (Criteria) this;
        }

        public Criteria andUserExt10IsNotNull() {
            addCriterion("user_ext10 is not null");
            return (Criteria) this;
        }

        public Criteria andUserExt10EqualTo(String value) {
            addCriterion("user_ext10 =", value, "userExt10");
            return (Criteria) this;
        }

        public Criteria andUserExt10NotEqualTo(String value) {
            addCriterion("user_ext10 <>", value, "userExt10");
            return (Criteria) this;
        }

        public Criteria andUserExt10GreaterThan(String value) {
            addCriterion("user_ext10 >", value, "userExt10");
            return (Criteria) this;
        }

        public Criteria andUserExt10GreaterThanOrEqualTo(String value) {
            addCriterion("user_ext10 >=", value, "userExt10");
            return (Criteria) this;
        }

        public Criteria andUserExt10LessThan(String value) {
            addCriterion("user_ext10 <", value, "userExt10");
            return (Criteria) this;
        }

        public Criteria andUserExt10LessThanOrEqualTo(String value) {
            addCriterion("user_ext10 <=", value, "userExt10");
            return (Criteria) this;
        }

        public Criteria andUserExt10Like(String value) {
            addCriterion("user_ext10 like", value, "userExt10");
            return (Criteria) this;
        }

        public Criteria andUserExt10NotLike(String value) {
            addCriterion("user_ext10 not like", value, "userExt10");
            return (Criteria) this;
        }

        public Criteria andUserExt10In(List<String> values) {
            addCriterion("user_ext10 in", values, "userExt10");
            return (Criteria) this;
        }

        public Criteria andUserExt10NotIn(List<String> values) {
            addCriterion("user_ext10 not in", values, "userExt10");
            return (Criteria) this;
        }

        public Criteria andUserExt10Between(String value1, String value2) {
            addCriterion("user_ext10 between", value1, value2, "userExt10");
            return (Criteria) this;
        }

        public Criteria andUserExt10NotBetween(String value1, String value2) {
            addCriterion("user_ext10 not between", value1, value2, "userExt10");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 07 16:47:44 KST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}