package com.fidelium.domain2;

public class UserHistory extends UserHistoryKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.type
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.type
     *
     * @return the value of user_history.type
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.type
     *
     * @param type the value for user_history.type
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    public void setType(String type) {
        this.type = type;
    }
}