package com.fidelium.dao2;

import com.fidelium.domain.ReceiveHistoryBatch;
import com.fidelium.domain2.ReceiveHistoryBatchExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ReceiveHistoryBatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_history_batch
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    long countByExample(ReceiveHistoryBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_history_batch
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int deleteByExample(ReceiveHistoryBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_history_batch
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int insert(ReceiveHistoryBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_history_batch
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int insertSelective(ReceiveHistoryBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_history_batch
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    List<ReceiveHistoryBatch> selectByExample(ReceiveHistoryBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_history_batch
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int updateByExampleSelective(@Param("record") ReceiveHistoryBatch record, @Param("example") ReceiveHistoryBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_history_batch
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int updateByExample(@Param("record") ReceiveHistoryBatch record, @Param("example") ReceiveHistoryBatchExample example);
}