package com.fidelium.dao2;

import com.fidelium.domain.TradeHistoryBatch;
import com.fidelium.domain2.TradeHistoryBatchExample;
import com.fidelium.domain2.TradeHistoryBatchKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TradeHistoryBatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_history_batch
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    long countByExample(TradeHistoryBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_history_batch
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int deleteByExample(TradeHistoryBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_history_batch
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int deleteByPrimaryKey(TradeHistoryBatchKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_history_batch
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int insert(TradeHistoryBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_history_batch
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int insertSelective(TradeHistoryBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_history_batch
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    List<TradeHistoryBatch> selectByExample(TradeHistoryBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_history_batch
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    TradeHistoryBatch selectByPrimaryKey(TradeHistoryBatchKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_history_batch
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int updateByExampleSelective(@Param("record") TradeHistoryBatch record, @Param("example") TradeHistoryBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_history_batch
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int updateByExample(@Param("record") TradeHistoryBatch record, @Param("example") TradeHistoryBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_history_batch
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int updateByPrimaryKeySelective(TradeHistoryBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_history_batch
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int updateByPrimaryKey(TradeHistoryBatch record);
}