package com.fidelium.dao2;

import com.fidelium.domain2.UserHistory;
import com.fidelium.domain2.UserHistoryExample;
import com.fidelium.domain2.UserHistoryKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_history
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    long countByExample(UserHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_history
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int deleteByExample(UserHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_history
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int deleteByPrimaryKey(UserHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_history
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int insert(UserHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_history
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int insertSelective(UserHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_history
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    List<UserHistory> selectByExample(UserHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_history
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    UserHistory selectByPrimaryKey(UserHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_history
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int updateByExampleSelective(@Param("record") UserHistory record, @Param("example") UserHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_history
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int updateByExample(@Param("record") UserHistory record, @Param("example") UserHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_history
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int updateByPrimaryKeySelective(UserHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_history
     *
     * @mbg.generated Tue Nov 07 16:47:44 KST 2017
     */
    int updateByPrimaryKey(UserHistory record);
}